
// agents
export const AGENTS_GET_LIST = 'AGENTS_GET_LIST';
export const AGENTS_GET_LIST_SUCCESS = 'AGENTS_GET_LIST_SUCCESS';
export const AGENTS_GET_LIST_FAILURE = 'AGENTS_GET_LIST_FAILURE';

// configs
export const CONFIG_UPDATE_IS_PROD = 'CONFIG_UPDATE_IS_PROD';

// layout
export const LAYOUT_SHOW_SPINNER = 'LAYOUT_SHOW_SPINNER';
export const LAYOUT_HIDE_SPINNER = 'LAYOUT_HIDE_SPINNER';
export const LAYOUT_LOGIN_MODAL_UPDATE = 'LAYOUT_LOGIN_MODAL_UPDATE';

// property
export const PROPERTIES_RESET_SEARCH = 'PROPERTIES_RESET_SEARCH';
export const PROPERTIES_GET_FEATURED_PROP = 'PROPERTIES_GET_FEATURED_PROP';
export const PROPERTIES_GET_FEATURED_PROP_SUCCESS = 'PROPERTIES_GET_FEATURED_PROP_SUCCESS';
export const PROPERTIES_GET_FEATURED_PROP_FAILURE = 'PROPERTIES_GET_FEATURED_PROP_FAILURE';
export const PROPERTIES_GET_RECOMMENDED = 'PROPERTIES_GET_RECOMMENDED';
export const PROPERTIES_GET_RECOMMENDED_SUCCESS = 'PROPERTIES_GET_RECOMMENDED_SUCCESS';
export const PROPERTIES_GET_RECOMMENDED_FAILURE = 'PROPERTIES_GET_RECOMMENDED_FAILURE';
export const PROPERTIES_GET_HOT = 'PROPERTIES_GET_HOT';
export const PROPERTIES_GET_HOT_SUCCESS = 'PROPERTIES_GET_HOT_SUCCESS';
export const PROPERTIES_GET_HOT_FAILURE = 'PROPERTIES_GET_HOT_FAILURE';
export const PROPERTIES_GET_NEW = 'PROPERTIES_GET_NEW';
export const PROPERTIES_GET_NEW_SUCCESS = 'PROPERTIES_GET_NEW_SUCCESS';
export const PROPERTIES_GET_NEW_FAILURE = 'PROPERTIES_GET_NEW_FAILURE';
export const PROPERTIES_SEARCH = 'PROPERTIES_SEARCH';
export const PROPERTIES_SEARCH_SUCCESS = 'PROPERTIES_SEARCH_SUCCESS';
export const PROPERTIES_SEARCH_FAILURE = 'PROPERTIES_SEARCH_FAILURE';

// search
export const SEARCH_CHANGE_FIELD = 'SEARCH_CHANGE_FIELD';
export const SEARCH_CHANGE_SORT_BY = 'SEARCH_CHANGE_SORT_BY';
export const SEARCH_CHANGE_PARAMS = 'SEARCH_CHANGE_PARAMS';
export const SEARCH_RESET_PARAMS = 'SEARCH_RESET_PARAMS';
export const SEARCH_GET_PRICE_TYPE = 'SEARCH_GET_PRICE_TYPE';
export const SEARCH_GET_PRICE_TYPE_SUCCESS = 'SEARCH_GET_PRICE_TYPE_SUCCESS';
export const SEARCH_GET_PRICE_TYPE_FAILURE = 'SEARCH_GET_PRICE_TYPE_FAILURE';

// user
export const USER_FETCH_DATA = 'USER_FETCH_DATA';
export const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS';
export const USER_FETCH_DATA_FAILURE = 'USER_FETCH_DATA_FAILURE';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
